{% set name = "kanaries-track" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kanaries_track-{{ version }}.tar.gz
  sha256: 2bc83512bee0b1f3720bf4e8dbf77c4264930a4eed3b1d6721e78e6b364e1873

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
  run:
    - python >=3.6
    - dateutils ==0.6.12
    - requests ==2.31.0
    - backoff ==2.2.1

test:
  imports:
    - kanaries_track
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/kanareis-track/
  summary: 'kanaries_track: track to kanaries data infra'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - longxiaofei
